name: C
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt -y install build-essential
      - name: Test linear search
        working-directory: search-algorithms/linear-search/c
        run: make test
