name: Go
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Test linear search
        working-directory: search-algorithms/linear-search/go
        run: go test -v ./...
      - name: Test binary search
        working-directory: search-algorithms/binary-search/go
        run: go test -v ./...
      - name: Test selection sort
        working-directory: sorting-algorithms/selection-sort/go
        run: go test -v ./...
