name: Rust
on:
  push:
    paths:
      - 'search-algorithms/linear-search/rust/**'
      - 'search-algorithms/binary-search/rust/**'
jobs:
  build:
    if: contains(github.event.head_commit.message, 'rust/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          # args: --release --all-features
